import type { Metadata } from 'next';
import { pretendard } from '@/shared/lib/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: '리빙옥션 :: Living auction',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={pretendard.variable}>
      <body className={`${pretendard.className} text-foreground bg-background`}>{children}</body>
    </html>
  );
}
