import type { Metadata, Viewport } from 'next';
import { pretendard } from '@/shared/lib/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: '리빙옥션 :: Living auction',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={`${pretendard.variable} h-full bg-background`}>
      <body className={`${pretendard.className} h-full text-foreground bg-gray-100`}>
        <div className='relative overflow-hidden bg-background md:max-w-md mx-auto min-h-screen w-full flex flex-col'>
          {children}
        </div>
      </body>
    </html>
  );
}
